name: Build Python Executable

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller yandex-music pylast

      - name: Build Executable
        run: |
          pyinstaller --onefile restore_scrobbles.py

      - name: Archive Executable
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-executable${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          path: |
            dist/restore_scrobbles${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  create_release:
    name: "Prelease"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            macos-latest-executable
            ubuntu-latest-executable
            windows-latest-executable.exe